controller_list:
  - name: "right_arm_jaco_trajectory_controller"
    action_ns: trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_joint_1
      - right_joint_2
      - right_joint_3
      - right_joint_4
      - right_joint_5
      - right_joint_6
      - right_joint_7

  - name: "left_arm_jaco_trajectory_controller"
    action_ns: trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_joint_1
      - left_joint_2
      - left_joint_3
      - left_joint_4
      - left_joint_5
      - left_joint_6
      - left_joint_7
